# The `src/module` directory is dedicated to only "nice" libraries (defined through add_library). No
# `firmware` targets and similar. Keep it civil, please

add_subdirectory(modbus)
add_subdirectory(onewire)
add_subdirectory(utils)
add_subdirectory(magic_optimizations)
add_subdirectory(raii)
add_subdirectory(nfc)
add_subdirectory(iso13239)
add_subdirectory(leds)
add_subdirectory(coding)
add_subdirectory(log_dev_null)
add_subdirectory(random)
add_subdirectory(fanctl)
add_subdirectory(signal_processing)
add_subdirectory(contactless_offset)
add_subdirectory(fifo_coder)
add_subdirectory(indx_head)
add_subdirectory(spi)
add_subdirectory(i2c)
add_subdirectory(cortex-m0-atomics)
add_subdirectory(otp)
add_subdirectory(tpis)
add_subdirectory(peripheries)
add_subdirectory(coroutines)
add_subdirectory(gui)

if(RTT_METRICS_ENABLED)
  add_subdirectory(rtt_metrics)
endif()
